name: Start tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Run tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64
      - name: Display Python version
        run: python --version
      - name: Run tests
        run: |
          python -m unittest test